name: Release Binary on Release Creation

on:
  release:
    types: [created]

jobs:
  build-and-upload:
    name: Build and Upload Binary
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.20'

      - name: Run Make Install
        run: make install

      - name: List files in cmd
        run: ls -al ./cmd

      - name: List files in cmd/injectived
        run: whereis injectived

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: /home/runner/go/bin/injectived
          asset_name: injectived-${{ github.event.release.tag_name }}
          asset_content_type: application/octet-stream